export interface IEmployee {
  firstName: string,
  middleName: string,
  lastName: string,
  Mobile: number,
  email: string,
  address: any,
  street: any,
  pinCode: number,
  city: string,
  state: string,
  country: string,
  id?: number,
  Title?: string,
  images?: string,
}
