export interface IEmployee {
  Title: string,
  firstName: string,
  middleName: string,
  lastName: string,
  Mobile: number,
  email: string,
  address: any,
  street: any,
  pinCode: number,
  city: string,
  state: string,
  country: string,
  id?: number,
}
